[package]
name = "PyStochOpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "PyStochOpt"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.1"
pyo3 = "0.22.0"
rand = "0.8.5"
rayon = "1.10.0"
